# Generated by Django 2.1.1 on 2018-09-14 00:29

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_address', models.CharField(blank=True, max_length=256, null=True)),
                ('relative_address', models.CharField(blank=True, max_length=256, null=True)),
                ('number_in_row', models.IntegerField(choices=[(1, 'Alone'), (2, 'With other'), (3, 'With 2 other')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('order_id', models.IntegerField(default=0, unique=True)),
                ('icon', models.ImageField(null=True, upload_to=courses.models.course_icon_directory)),
            ],
            options={
                'ordering': ('order_id',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('relative_address', models.CharField(blank=True, max_length=256)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(choices=[('md-play', 'Reading'), ('md-help', 'Question')], default=1, max_length=50)),
                ('text', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='courses.Lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
