# Generated by Django 2.1.1 on 2018-09-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('order_id',)},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
