# Generated by Django 2.1.1 on 2018-09-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180903_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='course',
            new_name='lesson',
        ),
    ]
