# Generated by Django 2.1.1 on 2018-09-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180921_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-id',)},
        ),
    ]
