# Generated by Django 2.1.1 on 2018-10-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181003_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('-order_id',)},
        ),
        migrations.AddField(
            model_name='part',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
