# Generated by Django 2.1.1 on 2018-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181016_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='school',
        ),
    ]
