# Generated by Django 2.1.1 on 2018-10-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20181016_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.School'),
        ),
    ]
