# Generated by Django 2.1.1 on 2018-10-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20181016_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
