# Generated by Django 2.1.1 on 2018-10-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20181018_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='school',
        ),
    ]
