# Generated by Django 2.1.1 on 2018-10-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('order_id',)},
        ),
        migrations.AddField(
            model_name='school',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='icon',
            field=models.CharField(choices=[('md-play', 'Reading'), ('md-help', 'Question')], default=1, max_length=50),
        ),
    ]
