# Generated by Django 2.1.1 on 2018-11-15 06:38

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20181025_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=courses.models.parts_image),
        ),
    ]
