# Generated by Django 2.1.1 on 2018-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20181116_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='icon_address',
        ),
    ]
