# Generated by Django 2.1.1 on 2018-12-14 09:07

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_course_icon_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.parts_image),
        ),
    ]
