# Generated by Django 2.1.1 on 2018-12-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20181214_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
