# Generated by Django 2.1.1 on 2019-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20190402_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='app_text_message',
        ),
        migrations.AddField(
            model_name='school',
            name='app_update_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
