# Generated by Django 2.1.1 on 2019-04-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_auto_20190402_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='app_destroy',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
