# Generated by Django 2.1.1 on 2019-04-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_school_app_destroy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='app_destroy',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
