# Generated by Django 2.1.1 on 2019-04-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20190403_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
