# Generated by Django 2.1.1 on 2019-04-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_school_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='app_destroy',
        ),
    ]
